
spring:
  datasource:
    platform: postgres
    password: letmein
    url: jdbc:postgresql://localhost:5432/handy
    username: fabio
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none #create
    properties:
      database: POSTGRES
      hibernate:
        #dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true